spring.application.name=KTB4_Finn_Week6


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:file:./data/community}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update

file.upload-dir=${FILE_UPLOAD_DIR:uploads}

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB




jwt.secret-key=${JWT_SECRET_KEY}
jwt.access-token-exp-seconds=${JWT_ACCESS_TOKEN_EXP_SECONDS:3600}
jwt.refresh-token-exp-seconds=${JWT_REFRESH_TOKEN_EXP_SECONDS:12096000}

spring.h2.console.enabled=true


#spring.jpa.show-sql=true
